---
targets:
- handler: "wol"
  source_url: "http://foo.bar.baz/*"
  target_url: "http://my-server-1.home:9090"
  methods: [GET, POST, DELETE, PATCH]
  options:
    mac: "00:1e:a5:1a:9d:11"
    timeout_s: 1

- handler: "plain"
  source_url: "http://another.hostname/with/a/specific/path"
  target_url: "https://google.com"
  methods: [GET]
  options:
    mac: "00:1e:a5:1a:9d:11"
    timeout_s: 2