---
targets:
- handler: "plain"
  target_url: "https://google.com"
  matches:
  - route: "/google-redirect"
- handler: "wol"
  target_url: "http://192.168.0.183:8096"
  methods: [GET, POST, DELETE, PATCH]
  options:
    mac: "ff:ff:ff:ff:ff"
    timeout_s: 2
  matches:
  - route: "/jelly/*"

