---
targets:
- handler: "wol"
  source_url: "http://ollamaproxy.xyz.net:11434/*"
  target_url: "http://aiserv.xyz.net:11434"
  methods: [GET, POST, DELETE, PATCH]
  options:
    mac: "a8:a1:59:08:b2:23"
    timeout_s: "30"
- handler: "wol"
  source_url: "http://ollamaproxy.xyz.net:8880/*"
  target_url: "http://aiserv.xyz.net:8880"
  methods: [GET, POST, DELETE, PATCH]
  options:
    mac: "a8:a1:59:08:b2:23"
    timeout_s: "30"
- handler: "wol"
  source_url: "http://llamaproxy.xyz.net:9292/*"
  target_url: "http://aiserv.xyz.net:9292"
  methods: [GET, POST, DELETE, PATCH]
  options:
    mac: "a8:a1:59:08:b2:23"
    timeout_s: "30"